#!/bin/bash
INTERFACE=`/sbin/ifconfig -a | sed 's/[ \t].*//;/^\(lo\|\)$/d'`
IPADDRESS=`/sbin/ifconfig $INTERFACE | grep "inet " | awk -F'[: ]+' '{ print $4 }'`
echo "aws ec2 authorize-security-group-ingress --group-name nems --protocol tcp --port 0-65535 --cidr $IPADDRESS/32";
aws ec2 authorize-security-group-ingress --group-name nems --protocol tcp --port 0-65535 --cidr $IPADDRESS/32
