#!/bin/bash

echo "Dumping local batch data to file"
locdump='mysqldump --host=hyrax.ohsu.edu -udavid -pnine1997'

$locdump cell sBatch NarfBatches >/tmp/NarfBatches.sql

echo "Reading batch data into remote db"
mysql --host=neuralprediction.org --database="cell" -udavid -pnine1997 < /tmp/NarfBatches.sql


