#!/bin/sh -f

# qsetload
# created svd 8/31/03
# script to update load for a given host

updateload() {
  local NAME=$1
  local EXT=$2
  local L1=$3
  local L5=$4
  local L15=$5

  echo "Setting load on name=$NAME,ext=$EXT to $L1/$L5/$L15"
  echo "update tComputer set load1=$L1,load5=$L5+second(now())/6000,load15=$L15,pingcount=0 where name='$NAME' AND ext='$EXT';"
  mysql --host=hyrax --user=david --password=nine1997 --raw --database=cell --execute="update tComputer set load1=$L1,load5=$L5+second(now())/6000,load15=$L15,pingcount=0 where name='$NAME' AND ext='$EXT';" 

  exit 0
}

#figure out the computer's name and extension
HOST=`hostname | tr '.' ' '`
SHHOST=`echo "$HOST ohsu" | awk '{c=split($0, s); for( n=1; n<=2; ++n) printf "%s ", s[n]  }'` 

# get load from the proc directory
LOADSTR=`cat /proc/loadavg`

# set the load
updateload $SHHOST $LOADSTR




