# This dict maps keywords to fragments of a modelspec
defaults = {'wc1': {'keyword': 'wc1',
                    'fn': 'nems.modules.weight_channels.weight_channels',
                    'prior': [],
                    'phi': []},
            'wc2': {'keyword': 'wc2',
                    'fn': 'nems.modules.fir.filter',
                    'prior': [],
                    'phi': []},
            'fir10x1': {'keyword': 'fir10x1',
                        'fn': 'nems.modules.fir.filter',
                        'prior': [],
                        'phi': []},
            'fir10x2': {'keyword': 'fir10x2',
                        'fn': 'nems.modules.fir.filter',
                        'prior': [],
                        'phi': []},
            'dexp1': {'keyword': 'dexp1',
                      'fn': 'nems.modules.nonlinearity.dexp',
                      'prior': [],
                      'phi': []},
            'dexp2': {'keyword': 'dexp2',
                      'fn': 'nems.modules.nonlinearity.dexp',
                      'prior': [],
                      'phi': []}}
