# This dict maps keywords to fragments of a modelspec
# TODO: added api tag for easy imports from nems.modules.api.
#       Maybe not the best approach? Just trying to get demo running for now.
defaults = {'wc1': {'keyword': 'wc1',
                    'fn': 'nems.modules.weight_channels.weight_channels',
                    'api': 'weight_channels',
                    'fn_kwargs': {},
                    'prior': [],
                    'phi': {}},
            'wc2': {'keyword': 'wc2',
                    'fn': 'nems.modules.weight_channels.weight_channels',
                    'api': 'weight_channels',
                    'fn_kwargs': {},
                    'prior': [],
                    'phi': {}},
            'fir10x1': {'keyword': 'fir10x1',
                        'fn': 'nems.modules.fir.fir_filter',
                        'api': 'fir_filter',
                        'fn_kwargs': {},
                        'prior': [],
                        'phi': {}},
            'fir10x2': {'keyword': 'fir10x2',
                        'fn': 'nems.modules.fir.fir_filter',
                        'api': 'fir_filter',
                        'fn_kwargs': {},
                        'prior': [],
                        'phi': {}},
            'dexp1': {'keyword': 'dexp1',
                      'fn': 'nems.modules.nonlinearity.double_exponential',
                      'api': 'double_exponential',
                      'fn_kwargs': {},
                      'prior': [],
                      'phi': {}},
            'dexp2': {'keyword': 'dexp2',
                      'fn': 'nems.modules.nonlinearity.double_exponential',
                      'api': 'double_exponential',
                      'fn_kwargs': {},
                      'prior': [],
                      'phi': {}}}